# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('avg_price', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('airBnbId', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('neighbourhood', models.CharField(max_length=254)),
                ('picture_url', models.URLField(max_length=254)),
                ('host_url', models.URLField(max_length=254)),
                ('host_name', models.CharField(max_length=254)),
                ('latitude', models.FloatField(max_length=254)),
                ('longitude', models.FloatField(max_length=254)),
                ('room_type', models.CharField(choices=[('Entire home/apt', 'Entire home/apt'), ('Private room', 'Private room'), ('Shared room', 'Shared room')], max_length=20)),
                ('price', models.FloatField(blank=True, null=True)),
                ('minimum_nights', models.IntegerField(blank=True, null=True)),
                ('number_of_reviews', models.IntegerField(blank=True, null=True)),
                ('review_scores_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField()),
                ('chechout_date', models.DateField()),
                ('destination', models.CharField(max_length=254)),
                ('guest_num', models.IntegerField(default=1)),
                ('num_of_results', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='availability',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negot.Listing'),
        ),
    ]
